<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title><?= $this->headTitle(); ?></title>
    <?= $this->headLink() ?>
    <?= $this->headScript() ?>

</head>

<body>

<p>MAIN LAYOUT</p>

<?= $this->content ?>

<?= $this->bodyScript() ?>

<div id="app"></div>
<script src="http://127.0.0.1:8080/js/bundle.js"></script>

</body>
</html>
